[tools]
go = "1.24.0"
node = "22.13.1"

[tasks]
install = { depends = ["install:*"] }
"install:workspaced" = "bash scripts/install-workspaced.sh"
codegen = "true"
lint = { run = "$HOME/.local/bin/workspaced codebase lint", depends = ["install:workspaced"] }
fmt = { run = "$HOME/.local/bin/workspaced codebase format", depends = ["install:workspaced"] }
test = "true"
ci = { depends = ["lint", "test"] }
